### ISSUE TITLE
v2.4.1 shows "code: 'MODULE_NOT_FOUND'".

### ISSUE THREAD

**Issue by robertdebock** [artis3n/ansible_galaxy_collection#141]
Using [this action](https://github.com/robertdebock/ansible-collection-roles/blob/master/.github/workflows/collection.yml):

```yaml
---

name: Build and Deploy Collection

on:
  push:

jobs:
  deploy:
    runs-on: "Ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Ansible Galaxy Collection
        uses: artis3n/ansible_galaxy_collection@v2.4.1
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
```

An error is returned:

```
Run artis3n/ansible_galaxy_collection@v2.4.1
  with:
    api_key: ***
    collection_dir: ./
    galaxy_config_file: galaxy.yml
/usr/bin/docker run --name a33c1e0073cbc558a485dbc2a2a878700ec94_025941 --label 8a33c1 --workdir /github/workspace --rm -e INPUT_API_KEY -e INPUT_COLLECTION_DIR -e INPUT_GALAXY_VERSION -e INPUT_GALAXY_CONFIG_FILE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/ansible-collection-roles/ansible-collection-roles":"/github/workspace" 8a33c1:e0073cbc558a485dbc2a2a878700ec94
node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module '@actions/core'
Require stack:
- /app/dist/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/app/dist/main.js:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/dist/main.js' ]
}
```

See [the error](https://github.com/robertdebock/ansible-collection-roles/runs/2618042136?check_suite_focus=true#step:4:25)

Maybe I made an error somewhere, but I guess something is wrong with the action.

BTW: Thanks for the action, it (normally) works great!
